-- SORUN: migration_003'te trip_stops uzerine eklenen
-- trip_stops_notify_insert/trip_stops_notify_update trigger'lari, her firma
-- girisi/cikisinda notify_trip_stop_event() -> gmail_access_token() ->
-- (token cache suresi dolmussa) dblink + pg_net polling zincirini AYNI
-- transaction icinde, SENKRON olarak calistiriyordu. Bu yuzden trip_stops
-- satirinin commit'i (dolayisiyla admin_web'in Realtime bildirimi) Gmail/
-- ag gecikmesine bagli kaliyordu: 'trips' tablosunda (fabrika giris/cikis)
-- hicbir trigger olmadigi icin o taraf hep aninda gelirken, 'trip_stops'
-- (firma giris/cikis) tarafi bazen saniyeler bazen de (dblink/ag sorununda)
-- cok daha uzun surebiliyor, bu da "60 saniye bekliyor" / "hic gelmiyor"
-- olarak gözlemleniyordu.
--
-- COZUM: Trigger artik mail gondermiyor, sadece hizli bir INSERT ile
-- 'notification_outbox' kuyruguna yaziyor (network/dblink YOK, tek bir
-- yerel INSERT). trip_stops yazisi boylece ARTIK HICBIR ZAMAN ag/Gmail
-- gecikmesi yasamaz; Realtime bildirimi fabrika ile ayni anda, aninda gider.
-- Mailler ayri, pg_cron ile her 30 saniyede bir calisan
-- process_notification_outbox() tarafindan arka planda gonderiliyor.

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  to_email text not null,
  subject text not null,
  body text not null,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  attempt_count int not null default 0,
  last_error text
);

create index if not exists notification_outbox_pending_idx
  on public.notification_outbox (created_at)
  where sent_at is null;

create or replace function public.notify_trip_stop_event()
 returns trigger
 language plpgsql
 security definer
 set search_path to public
as $function$
declare
  v_islem text;
  v_sofor text;
  v_plaka text;
  v_gidilen text;
  v_konu text;
  v_govde text;
  v_alici record;
  v_gonderilenler uuid[] := '{}';
begin
  begin
    v_islem := case when TG_OP = 'INSERT' then 'Firma Girişi' else 'Firma Çıkışı' end;

    select p.full_name, v.plaka into v_sofor, v_plaka
    from public.trips t
    join public.profiles p on p.id = t.driver_id
    join public.vehicles v on v.id = t.vehicle_id
    where t.id = new.trip_id;

    v_gidilen := coalesce(
      nullif(trim(both ' / ' from coalesce(new.gidilen_il, '') || ' / ' || coalesce(new.gidilen_ilce, '')), ''),
      new.gidilen_sirket_free,
      '-'
    );

    v_konu := v_islem || ' - ' || coalesce(v_sofor, '-') || ' - ' || coalesce(v_plaka, '-');
    v_govde := 'Şoför: ' || coalesce(v_sofor, '-') || E'\n' ||
               'Plaka: ' || coalesce(v_plaka, '-') || E'\n' ||
               'İşlem: ' || v_islem || E'\n' ||
               'Gidilen Yer: ' || v_gidilen || E'\n' ||
               'Zaman: ' || to_char(now(), 'DD.MM.YYYY HH24:MI');

    -- Alici 1: bu duragin "Talep Eden Kisi"sine karsilik gelen hesap.
    for v_alici in
      select p.id, p.notification_email
      from public.requesters r
      join public.profiles p on p.id = r.profile_id
      where r.id = new.requester_id
        and p.role in ('office', 'manager', 'admin')
        and p.notification_email is not null
    loop
      insert into public.notification_outbox (to_email, subject, body)
      values (v_alici.notification_email, v_konu, v_govde);
      v_gonderilenler := array_append(v_gonderilenler, v_alici.id);
    end loop;

    -- Alici 2: bildirim tercihi acik olan tum yonetici/admin'ler.
    for v_alici in
      select p.id, p.notification_email
      from public.profiles p
      where p.role in ('manager', 'admin')
        and p.email_bildirim_aktif = true
        and p.notification_email is not null
        and not (p.id = any(v_gonderilenler))
    loop
      insert into public.notification_outbox (to_email, subject, body)
      values (v_alici.notification_email, v_konu, v_govde);
    end loop;
  exception when others then
    raise warning 'notify_trip_stop_event basarisiz: %', sqlerrm;
  end;

  return new;
end;
$function$;

-- Kuyruktaki bekleyen mailleri gonderir. Token/dblink/ag gecikmesi ARTIK
-- SADECE burada olur; trip_stops yazisini hicbir sekilde etkilemez.
create or replace function public.process_notification_outbox()
 returns void
 language plpgsql
 security definer
 set search_path to public, net, vault, extensions
as $function$
declare
  v_row record;
  v_access_token text;
begin
  if not exists (
    select 1 from public.notification_outbox where sent_at is null and attempt_count < 5
  ) then
    return;
  end if;

  begin
    v_access_token := public.gmail_access_token();
  exception when others then
    raise warning 'process_notification_outbox: token alinamadi: %', sqlerrm;
    return;
  end;

  for v_row in
    select * from public.notification_outbox
    where sent_at is null and attempt_count < 5
    order by created_at
    limit 50
  loop
    begin
      perform public.send_notification_email(v_access_token, v_row.to_email, v_row.subject, v_row.body);
      update public.notification_outbox set sent_at = now() where id = v_row.id;
    exception when others then
      update public.notification_outbox
      set attempt_count = attempt_count + 1, last_error = sqlerrm
      where id = v_row.id;
    end;
  end loop;
end;
$function$;

revoke execute on function public.process_notification_outbox() from public, anon, authenticated;

create extension if not exists pg_cron;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'process_notification_outbox') then
    perform cron.unschedule('process_notification_outbox');
  end if;
end $$;

select cron.schedule(
  'process_notification_outbox',
  '30 seconds',
  $$select public.process_notification_outbox();$$
);
